"""Heuristic confidence scorer for SLM responses.

Produces a 0.0–1.0 confidence score by penalising common quality
signals: emptiness, uncertainty language, bad length, lack of
structure, and repetition.
"""

import re

from app.utils.logger import get_logger

logger = get_logger(__name__)

_UNCERTAINTY_PHRASES: list[str] = [
    "i'm not sure",
    "i don't know",
    "it's unclear",
    "i cannot",
    "i'm unable",
    "possibly",
    "might be",
    "not enough information",
    "i don't have",
]

_STRUCTURE_TASKS: set[str] = {"summarization", "extraction"}

# ── weight table ────────────────────────────────────────────────────
_W_EMPTY = 0.10
_W_UNCERTAINTY = 0.30
_W_LENGTH = 0.20
_W_STRUCTURE = 0.25
_W_REPETITION = 0.15


def _penalty_empty(response: str) -> float:
    """1.0 if the response is empty, None-ish, or trivially short."""
    if not response or len(response.strip()) < 10:
        return 1.0
    return 0.0


def _penalty_uncertainty(response: str) -> float:
    """Penalise hedging / refusal language."""
    lower = response.lower()
    matches = sum(1 for phrase in _UNCERTAINTY_PHRASES if phrase in lower)
    return min(matches / 3, 1.0)


def _penalty_length(response: str) -> float:
    """Penalise responses that are too short or excessively long."""
    length = len(response.strip())
    if length < 50:
        return 0.8
    if length > 5000:
        return 0.4
    return 0.0


def _penalty_structure(response: str, task_type: str) -> float:
    """Penalise lack of multi-sentence / structured output."""
    # Count sentences (period followed by whitespace or end-of-string)
    sentences = re.split(r"\.\s+|\.\Z", response.strip())
    # Filter out empty fragments from the split
    sentences = [s for s in sentences if s.strip()]
    sentence_count = len(sentences)

    if sentence_count < 2:
        return 1.0

    # For structure-sensitive tasks, reward bullet points / line breaks
    if task_type.lower() in _STRUCTURE_TASKS:
        has_bullets = bool(re.search(r"[\-\*•]\s", response))
        has_newlines = "\n" in response.strip()
        if not (has_bullets or has_newlines):
            return 0.4
    return 0.0


def _penalty_repetition(response: str) -> float:
    """Penalise repeated sentences."""
    sentences = [
        s.strip().lower()
        for s in re.split(r"[.!?]+", response)
        if s.strip()
    ]
    if not sentences:
        return 1.0

    from collections import Counter

    counts = Counter(sentences)
    repeated = sum(c for c in counts.values() if c >= 2)
    return min(repeated / len(sentences), 1.0)


def score_confidence(response: str, task_type: str) -> float:
    """Score SLM output quality via lightweight heuristics.

    Args:
        response: The text generated by the SLM.
        task_type: The analysis task category.

    Returns:
        A float in ``[0.0, 1.0]`` where 1.0 is highest confidence.
    """
    p_empty = _penalty_empty(response or "")
    p_uncert = _penalty_uncertainty(response or "")
    p_len = _penalty_length(response or "")
    p_struct = _penalty_structure(response or "", task_type)
    p_rep = _penalty_repetition(response or "")

    weighted_penalty = (
        _W_EMPTY * p_empty
        + _W_UNCERTAINTY * p_uncert
        + _W_LENGTH * p_len
        + _W_STRUCTURE * p_struct
        + _W_REPETITION * p_rep
    )

    confidence = max(0.0, min(1.0, 1.0 - weighted_penalty))

    logger.info(
        "Confidence %.2f  | empty=%.2f  uncert=%.2f  len=%.2f  "
        "struct=%.2f  rep=%.2f  task=%s",
        confidence,
        p_empty,
        p_uncert,
        p_len,
        p_struct,
        p_rep,
        task_type,
    )
    return confidence
